# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dagu < Formula
  desc "A compact, portable, and language-agnostic workflow engine"
  homepage "https://github.com/dagu-org/dagu"
  version "2.9.0"
  license "GNU General Public License v3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dagucloud/dagu/releases/download/v2.9.0/dagu_2.9.0_darwin_amd64.tar.gz"
      sha256 "8b4f8591ba61de2f372c8cf781a0ae787a6115e297cd90587369a5af4fe99175"

      define_method(:install) do
        bin.install "dagu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dagucloud/dagu/releases/download/v2.9.0/dagu_2.9.0_darwin_arm64.tar.gz"
      sha256 "c6618d0bb05f33a3b137ada84fff6a3324b743b006144ffe8adb15a2b661687c"

      define_method(:install) do
        bin.install "dagu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dagucloud/dagu/releases/download/v2.9.0/dagu_2.9.0_linux_amd64.tar.gz"
      sha256 "25ab67afa84d5824d5cde4e02f95030417c3d7245ea90272ddd407900f6fa1fd"
      define_method(:install) do
        bin.install "dagu"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dagucloud/dagu/releases/download/v2.9.0/dagu_2.9.0_linux_armv6.tar.gz"
      sha256 "c10ea3681a469d4593e3cf463968c6b7a250cff337d81abb45343b53435feba4"
      define_method(:install) do
        bin.install "dagu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dagucloud/dagu/releases/download/v2.9.0/dagu_2.9.0_linux_arm64.tar.gz"
      sha256 "78b050fc239e33431cbdef0f3754f45058fa568e94bec5aef1cdf6987a184688"
      define_method(:install) do
        bin.install "dagu"
      end
    end
  end

  service do
    run [opt_bin/"dagu", "start-all"]
    keep_alive true
    error_log_path var/"log/dagu.log"
    log_path var/"log/dagu.log"
    working_dir var
  end
end
