# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dagu < Formula
  desc "A compact, portable, and language-agnostic workflow engine"
  homepage "https://github.com/dagucloud/dagu"
  version "2.11.3"
  license "GNU General Public License v3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dagucloud/dagu/releases/download/v2.11.3/dagu_2.11.3_darwin_amd64.tar.gz"
      sha256 "c1c19d8fbe8baee7c5dc1a0272661df605c48d9cb760d770103ad4e314a379ca"

      define_method(:install) do
        bin.install "dagu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dagucloud/dagu/releases/download/v2.11.3/dagu_2.11.3_darwin_arm64.tar.gz"
      sha256 "8604cbbef23908ef4b6bf055bc10db3d14fae5edf899b635d8fdca0d8a09f59c"

      define_method(:install) do
        bin.install "dagu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dagucloud/dagu/releases/download/v2.11.3/dagu_2.11.3_linux_amd64.tar.gz"
      sha256 "0035dd86125c1151eec393e2280ce107607bda78ce1e5496340a16713dda88f1"
      define_method(:install) do
        bin.install "dagu"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dagucloud/dagu/releases/download/v2.11.3/dagu_2.11.3_linux_armv6.tar.gz"
      sha256 "bf7282761fa61775518451c59488bb92b2c1fff054f587996eb8fb47e93e3cd0"
      define_method(:install) do
        bin.install "dagu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dagucloud/dagu/releases/download/v2.11.3/dagu_2.11.3_linux_arm64.tar.gz"
      sha256 "8a63ea5e9ce494d02a97c838ae2cb12f82623120d033add9923044ca93f059d1"
      define_method(:install) do
        bin.install "dagu"
      end
    end
  end

  service do
    run [opt_bin/"dagu", "start-all"]
    keep_alive true
    error_log_path var/"log/dagu.log"
    log_path var/"log/dagu.log"
    working_dir var
  end
end
