# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dagu < Formula
  desc "A compact, portable, and language-agnostic workflow engine"
  homepage "https://github.com/dagu-org/dagu"
  version "2.7.9"
  license "GNU General Public License v3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dagucloud/dagu/releases/download/v2.7.9/dagu_2.7.9_darwin_amd64.tar.gz"
      sha256 "25372a69f876fdaa4c94c96046169651ea891fb353e52cbe7701827b39ebd371"

      define_method(:install) do
        bin.install "dagu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dagucloud/dagu/releases/download/v2.7.9/dagu_2.7.9_darwin_arm64.tar.gz"
      sha256 "196d1f91447f74943ad2932c9c9b0a07963b471bdd7970d686d59011c175146b"

      define_method(:install) do
        bin.install "dagu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dagucloud/dagu/releases/download/v2.7.9/dagu_2.7.9_linux_amd64.tar.gz"
      sha256 "285a7246b40e8d89443527377b63685e188a22681b640fd00fa908de37e69994"
      define_method(:install) do
        bin.install "dagu"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dagucloud/dagu/releases/download/v2.7.9/dagu_2.7.9_linux_armv6.tar.gz"
      sha256 "fbeb9f639fac102646dc5c6c354f9be168c22994464234455776efc1ba242e3a"
      define_method(:install) do
        bin.install "dagu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dagucloud/dagu/releases/download/v2.7.9/dagu_2.7.9_linux_arm64.tar.gz"
      sha256 "cb80b88c832126e162cca91f7e88a5349d896c1398a53932a04462db43e35476"
      define_method(:install) do
        bin.install "dagu"
      end
    end
  end

  service do
    run [opt_bin/"dagu", "start-all"]
    keep_alive true
    error_log_path var/"log/dagu.log"
    log_path var/"log/dagu.log"
    working_dir var
  end
end
